export const transactionCategories = [
  'Food',
  'Transport',
  'Housing',
  'Health',
  'Education',
  'Entertainment',
  'Subscriptions',
  'Shopping',
  'Utilities',
  'Personal Care',
  'Gifts',
  'Travel',
  'Fitness',
  'Insurance',
  'Banking Fees',
  'Home',
  'Donations',
  'Salary',
  'Freelance',
  'Investment',
  'Other',
];
